chore: config husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,9 +1,24 @@
-npm run lint ||
+# bash echo color
+RED='\033[1;31m'
+GREEN='\033[1;32m'
+BLUE='\033[1;36m'
+BOLD='\033[1;37m'
+NC='\033[0m'
+
+echo "🚧🏗️  ${BOLD}Checking format, lint and types in your project before committing${NC}"
+# Check Prettier standards
+npm run check-format ||
 (
-  echo "❌ - npm run lint Failed. - ❌\n View the errors above in order to fix them!"
-  false;
+    echo "❌🟨 Prettier Check ${RED}Failed${NC}. 🟨❌\n Run ${BLUE}npm run format${NC}, add changes and try commit again.";
+    false;
 )
 
+# Check ESLint Standards
+npm run lint ||
+(
+    echo "❌🟪 ESLint Check ${RED}Failed${NC}. 🟪❌\n Make the required changes listed above, add changes and try to commit again."
+    false;
+)
 (
   echo "✅ - Code successfully linted, now applying default formatting to the code.."
   true;
